build:
	javac supermarket/*.java
	javac supermarket/gui/SupermarketGUI.java

run:
	java supermarket.Test

runGUI:
	java supermarket.gui.SupermarketGUI

clean:
	rm supermarket/*.class
	rm supermarket/gui/*class
	rm output.txt
